In [1]:
sequence = "ATGCGATCGATCGATCG"

print(sequence)

ATGCGATCGATCGATCG

In [2]:
print(len(sequence))

17

In [3]:
gene = "TP53"
organism = "Homo sapiens"
sequence = "ATGCGATCGATCG"
length = len(sequence)

print("gene:",gene)
print("organism:",organism)
print("sequence:",sequence)
print("length:",length)

gene: TP53
organism: Homo sapiens
sequence: ATGCGATCGATCG
length: 13

In [4]:
base=input("Enter a nucleotide(A/T/C/G)")
if base=="A":
    print("Adenine")
elif base=="T":
    print("Thymine")
elif base=="G":
    print("Guanine")
elif base=="C":
    print("Cvtosine")
else:
    print("Invalid nucleotide")

Enter a nucleotide(A/T/C/G)A
Adenine

In [5]:
sequence = "ATGCGATCGX"
if "X" in sequence:
    print("Invalid DNA sequence")
else:
    print("Valid DNA sequence")

Invalid DNA sequence

In [6]:
sequence = "ATGCGATCG"
valid_bases = "ATGC"
valid = True

for base in sequence:
    if base not in valid_bases:
        valid = False
if valid:
    print("valid DNA sequence")
else:
    print("Invalid DNA sequence")

valid DNA sequence

In [7]:
sequence = "ATGCGATC"

for i in sequence:
    print(i)

A
T
G
C
G
A
T
C

In [8]:
sequence = "ATGCGATC"

count = 0

for base in sequence:
    if base == "A":
        count=count+1
print("Number of A:",count)

Number of A: 2

In [9]:
sequence = "ATGCGATC"

print("A:",sequence.count("A"))
print("T:",sequence.count("T"))
print("G:",sequence.count("G"))
print("C:",sequence.count("C"))

A: 2
T: 2
G: 2
C: 2

In [10]:
genes=["BRCA","TP53","EGFR","KRAS"]
print(genes)

['BRCA', 'TP53', 'EGFR', 'KRAS']

In [11]:
import numpy as np
expression = np.array([12.5,15.2,8.4,20.1,18.7])

print("Mean:",np.mean(expression))
print("Max:",np.max(expression))
print("Min:",np.min(expression))

Mean: 14.98
Max: 20.1
Min: 8.4

In [12]:
gene={
    "name":"BRCA1",
    "organism":"Homo sapiens",
    "chromosome":"17",
    "function":"DNA Repair"
}
print(gene)
print(gene["name"])
print(gene["organism"])
print(gene["chromosome"])
print(gene["function"])

{'name': 'BRCA1', 'organism': 'Homo sapiens', 'chromosome': '17', 'function': 'DNA Repair'}
BRCA1
Homo sapiens
17
DNA Repair

In [13]:
gene["sequence"]="ATGCGATCGX"
print(gene)

{'name': 'BRCA1', 'organism': 'Homo sapiens', 'chromosome': '17', 'function': 'DNA Repair', 'sequence': 'ATGCGATCGX'}

In [14]:
genes={
    "BRCA1": {
        "organism":"Homo sapiens",
        "chromosome":"17"
    },
    
    "TP53": {
        "organism":"Homo sapiens",
        "chromosome":"17"
    },
    
     "EGFR": {
        "organism":"Homo sapiens",
        "chromosome":"17"
    }
}
print(genes)

{'BRCA1': {'organism': 'Homo sapiens', 'chromosome': '17'}, 'TP53': {'organism': 'Homo sapiens', 'chromosome': '17'}, 'EGFR': {'organism': 'Homo sapiens', 'chromosome': '17'}}

In [15]:
print(genes["BRCA1"])
print(genes["TP53"]["chromosome"])

{'organism': 'Homo sapiens', 'chromosome': '17'}
17

In [16]:
import pandas as pd
data={
    "Gene":["BRCA1","TP53","EGFR","KRAS"],
    "Organism":["Human","Human","Human","Human"],
    "Length":[1200,1500,1100,900],
    "GC_content":[45.2,51.3,48.7,42.1]
}
df=pd.DataFrame(data)
print(df)

    Gene Organism  Length  GC_content
0  BRCA1    Human    1200        45.2
1   TP53    Human    1500        51.3
2   EGFR    Human    1100        48.7
3   KRAS    Human     900        42.1

In [17]:
df.head()

    Gene Organism  Length  GC_content
0  BRCA1    Human    1200        45.2
1   TP53    Human    1500        51.3
2   EGFR    Human    1100        48.7
3   KRAS    Human     900        42.1

In [18]:
df.shape

(4, 4)

In [19]:
df.info

<bound method DataFrame.info of     Gene Organism  Length  GC_content
0  BRCA1    Human    1200        45.2
1   TP53    Human    1500        51.3
2   EGFR    Human    1100        48.7
3   KRAS    Human     900        42.1>

In [20]:
df.describe()

       Length  GC_content
count     4.0     4.00000
mean   1175.0    46.82500
std     250.0     4.02109
min     900.0    42.10000
25%    1050.0    44.42500
50%    1150.0    46.95000
75%    1275.0    49.35000
max    1500.0    51.30000

In [21]:
df.tail()

    Gene Organism  Length  GC_content
0  BRCA1    Human    1200        45.2
1   TP53    Human    1500        51.3
2   EGFR    Human    1100        48.7
3   KRAS    Human     900        42.1

In [22]:
df.columns

Index(['Gene', 'Organism', 'Length', 'GC_content'], dtype='object')

In [23]:
df["Gene"]

0    BRCA1
1     TP53
2     EGFR
3     KRAS
Name: Gene, dtype: object

In [24]:
#filtering the biological data
df[df["GC_content"]>45]

    Gene Organism  Length  GC_content
0  BRCA1    Human    1200        45.2
1   TP53    Human    1500        51.3
2   EGFR    Human    1100        48.7

In [25]:
#sorting
df.sort_values("GC_content")
df.sort_values("GC_content",ascending=False)

    Gene Organism  Length  GC_content
1   TP53    Human    1500        51.3
2   EGFR    Human    1100        48.7
0  BRCA1    Human    1200        45.2
3   KRAS    Human     900        42.1

In [26]:
#add new column
df["Length_kb"]=df["Length"]/100

print(df)

    Gene Organism  Length  GC_content  Length_kb
0  BRCA1    Human    1200        45.2       12.0
1   TP53    Human    1500        51.3       15.0
2   EGFR    Human    1100        48.7       11.0
3   KRAS    Human     900        42.1        9.0

In [27]:
#Find gens with length greater than 1100
df[df["Length"]>1100]

    Gene Organism  Length  GC_content  Length_kb
0  BRCA1    Human    1200        45.2       12.0
1   TP53    Human    1500        51.3       15.0

In [28]:
#count genes with length greater than 1000
(df["Length"]>1000).sum()

3

In [29]:
#find genes with both length > 1000 and GC content > 45
df[(df["Length"]>1000) & (df["GC_content"]>45)]

    Gene Organism  Length  GC_content  Length_kb
0  BRCA1    Human    1200        45.2       12.0
1   TP53    Human    1500        51.3       15.0
2   EGFR    Human    1100        48.7       11.0

In [33]:
#compare average GC content by organism
df.groupby("Organism")["GC_content"].mean()

Organism
Human    46.825
Name: GC_content, dtype: float64